// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removednullablefromstartdateandstarttimeinEventModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removednullablefromstartdateandstarttimeinEventModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201902232005006_removed nullable from startdate and starttime in Event Model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
