// <auto-generated />
namespace Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identityinsertsettooffinuseraccounttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityinsertsettooffinuseraccounttable));
        
        string IMigrationMetadata.Id
        {
            get { return "201902221020171_identity-insert set to off in useraccount table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
